function [fitresult, gof] = createFit(X, Y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'Negative Sigmoidal Fit' fit:
%      X Input : X
%      Y Output: Y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Dec-2015 18:28:57


%% Fit: 'Negative Sigmoidal Fit'.
[xData, yData] = prepareCurveData( X, Y );

% Set up fittype and options.
ft = fittype( '-A / (1 + exp(-r * (x - x0)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.DiffMinChange = 1e-10;
opts.Display = 'Off';
opts.MaxFunEvals = 900;
opts.MaxIter = 10000;
opts.StartPoint = [0.655740699156587 0.0357116785741896 0.849129305868777];
opts.TolFun = 1e-09;
opts.TolX = 1e-09;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Negative Sigmoidal Fit' );
plot( fitresult, xData, yData );
% Label axes
title 'Negative Logistic Fit'
xlabel 'Volume (uL)'
ylabel 'Height (mm)'
grid off


