function [fitresult, gof] = expfitCooling(time, temp)
%CREATEFIT1(TIME,TEMP)
%  Create a fit.
%
%  Data for 'exponential fit cooling' fit:
%      X Input : time
%      Y Output: temp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.h = 3.04494*10^{-6} \sqrt{1.56624*10^{11} V - 6.26495*10^{11}}$$

%  Auto-generated by MATLAB on 30-Dec-2015 23:52:06


%% Fit: 'exponential fit cooling'.
[xData, yData] = prepareCurveData( time, temp );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [48.9065369862045 -0.126835573556153];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'exponential fit cooling' );
h = plot( fitresult, xData, yData );
legend( h, 'temp vs. time', 'exponential fit cooling', 'Location', 'NorthEast' );
% Label axes
xlabel time
ylabel temp
grid on


